# -*- mode: ruby -*-
# vi: set ft=ruby :
 
Vagrant.configure("2") do |config|
  config.vm.define "abiariS" do |server|
    server.vm.box = "centos/7"
    server.vm.hostname = "abiariS"
    server.vm.network "private_network", ip: "192.168.42.110"
    server.vm.provision "shell", path: "./scripts/k3s-server.sh"
    server.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", 1024]
      vb.customize ["modifyvm", :id, "--cpus", 1]
      vb.customize ["modifyvm", :id, "--name", "abiariS"]
    end
  end
end
